name: Build static site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BG_KEY: ${{ secrets.BACKGROUNDIMGKEY }}
      W_KEY: ${{ secrets.WEATHERKEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create config.js with secrets
        run: |
          echo "const CONFIG = {" > config.js
          echo "  weatherKey: \"${{ secrets.WEATHERKEY }}\"," >> config.js
          echo "  backgroundImgKey: \"${{ secrets.BACKGROUNDIMGKEY }}\"" >> config.js
          echo "};" >> config.js
          echo "export default CONFIG;" >> config.js

      - name: List files (for demo)
        run: ls -la

      - name: Deploy (optional)
        run: echo "Deploy your site here (e.g., Netlify, FTP, etc.)"
