name: Build static site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEATHER_KEY: ${{ secrets.WEATHERKEY }}
      BACKGROUND_KEY: ${{ secrets.BACKGROUNDIMGKEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create config.js with secrets
        run: |
          echo "const CONFIG = {" > config.js
          echo "  weatherKey: \"${{ secrets.WEATHER_KEY }}\"," >> config.js
          echo "  backgroundImgKey: \"${{ secrets.BACKGROUND_KEY }}\"" >> config.js
          echo "};" >> config.js
          echo "export default CONFIG;" >> config.js

      - name: List files (for demo)
        run: ls -la

      - name: Deploy
        run: echo "Deploy your site here (e.g., Netlify, Vercel, etc.)"
